import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import hljs from "highlight.js";
import "highlight.js/styles/github.css";

import React from "react";
import { Toaster } from "@ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
